# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d2a3d034c6acd03d4464bf49187f2399eb0d2dca64d43e50d0c725e13f999d19e7a8f217586fa1d71868c2e4c6b5c0c81bb3649ee6de40ab452527fe98799dd

test:
  secret_key_base: 9157a17c548d617e360fb48ef2b8ee267267acea75d51b682831e1076fc2d1e5ddd55448655b4a25695792e041919b28d7ff2bb3d58ffa4c68f31e3f6cc31748

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
